name: Build & Deploy
on:
  push:
    branches:
      - master
      - staging

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: website
    steps:

      - name: Login to Registry
        run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if ! [ "$BRANCH" == "master" ]; then IMAGE_TAG="$IMAGE_TAG-$BRANCH; fi
          docker build --build-arg BRANCH=$BRANCH -t docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG} .

      - name: Publish image
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}

      - name: Logout
        run: docker logout docker.pkg.github.com

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      DEPLOYMENT: website
      CONTAINER: website
      IMAGE_NAME: website
    steps:

      - name: Set up config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONFIG_STAGING: ${{ secrets.KUBE_CONFIG_STAGING }}
        run: |
          if [ "${GITHUB_REF#refs/heads/}" == "staging" ]; then KUBE_CONFIG=$KUBE_CONFIG_STAGING; fi
          mkdir -p ${HOME}/.kube
          export KUBECONFIG=${HOME}/.kube/config
          echo $KUBE_CONFIG | base64 -d > $KUBECONFIG

      - name: Deploy image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if ! [ "$BRANCH" == "master" ]; then IMAGE_TAG="$IMAGE_TAG-$BRANCH; fi
          kubectl set image deployment/${DEPLOYMENT} ${CONTAINER}=docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Check rollout
        if: success()
        run: kubectl rollout status deployment/${DEPLOYMENT} -w --timeout=5m

      - name: Roll back
        if: failure()
        run: kubectl rollout undo deployment/${DEPLOYMENT}
