name: Lint & Test
on:
  push:
    paths:
      - '*.go'
      - '*/*.go'
      - '*/*/*.go'
      - '*/*/*/*.go'
      - 'static/resources/js/*.js'
      - 'go.mod'
      - 'go.sum'
      - 'revive.toml'
      - '.eslintrc.json'
      - '.eslintignore'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/lint-test.yaml'

jobs:

  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'

    - name: Check out
      uses: actions/checkout@v1

    - name: Run Revive Action
      uses: docker://morphy/revive-action:v1
      with:
        config: revive.toml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check formatting
      run: test -z $(gofmt -l .) || (gofmt -l . && exit 1)

  js-lint:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v1

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install packages
      run: npm i

    - name: Run linter
      run: npm run lint
